version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest-browsers

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependecies-{{checksum "package.json"}}
            - v1-dependecies-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm run build

  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependecies-{{checksum "package.json"}}
            - v1-dependecies-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm run test
      - run: npm run e2e

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
