version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest

jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  test:
    jobs:
      - test
      - build:
          requires:
            - test
